DROP DATABASE IF EXISTS $MYSQL_DATABASE;
CREATE DATABASE $MYSQL_DATABASE;
GRANT ALL ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'db' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL ON test_.* TO '$MYSQL_USER'@'db' IDENTIFIED BY '$MYSQL_PASSWORD';